name: Build Bee BSP

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
         submodules: recursive

    - name: Build the Docker image
      run: ./build-container.sh

    - name: Build the product
      run: ./build-product.sh

    - name: Archive the product
      uses: actions/upload-artifact@v4
      with:
              name: Product
              path: /workdir/build/tmp/deploy/images/*
